application_student_homepage:
    path:     /addStudent
    defaults: { _controller: applicationStudentBundle:Default:index }

application_student_insertpage:
    path:     /AddStudentControl
    defaults: { _controller: applicationStudentBundle:Student:addStudent }

application_student_sport_detail_insertpage:
    path:     /addStudentspd
    defaults: { _controller: applicationStudentBundle:SportInvolve:index }


application_sport_involve_controlpage:
    path:     /AddStudentSPDControl
    defaults: { _controller: applicationStudentBundle:SportInvolve:addSportInvolve}

application_getStudentDetailPage:
    path:     /getStudentDetail
    defaults: { _controller: applicationStudentBundle:Student:getStudentDetails}

application_studentRequestPage:
    path:     /studentRequest
    defaults: { _controller: applicationStudentBundle:StudentRequest:index}


application_studentRequestSubmitPage:
    path:     /submitStudentRequest
    defaults: { _controller: applicationStudentBundle:StudentRequest:addStudentRequest}