application_locations:
    resource: "@applicationLocationsBundle/Resources/config/routing.yml"
    prefix:   /

sport:
    resource: "@SportBundle/Resources/config/routing.yml"
    prefix:   /

applicationequipment:
    resource: "@applicationequipmentBundle/Resources/config/routing.yml"
    prefix:   /

application_student:
    resource: "@applicationStudentBundle/Resources/config/routing.yml"
    prefix:   /

application_main:
    resource: "@applicationMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
