application_main_homepage:
    path:     /
    defaults: { _controller: applicationMainBundle:Default:index }

applicationMainAdminUI:
    path:     /adminMainPanel
    defaults: {_controller: applicationMainBundle:MainTemplate:mainTemplateAdmin }

applicationMainUserUI:
    path:     /userMainPanel
    defaults: {_controller: applicationMainBundle:MainTemplate:mainTemplateUser }

applicationTemplate:
    path:     /template
    defaults: { _controller: applicationMainBundle:MainTemplate:templateTest }