applicationequipment_homepage:
    path:     /
    defaults: { _controller: applicationequipmentBundle:Default:index }
applicationequipment_addEquip:
    path:     /add
    defaults: { _controller: applicationequipmentBundle:form:saveEquipment }
applicationequipment_addEquipForm:
    path:     /addEquip
    defaults: { _controller: applicationequipmentBundle:form:add }
applicationequipment_reportDamage:
    path:     /DamageDesc
    defaults: { _controller: applicationequipmentBundle:form:damageView }

applicationequipment_reportDamageView:
    path:     /saveDamage
    defaults: { _controller: applicationequipmentBundle:form:damageReport }
applicationequipment_addNewEquipView:
    path:     /addNewEquip
    defaults: { _controller: applicationequipmentBundle:form:addNewEquipment }
applicationequipment_addNewEquipsave:
    path:     /addNew
    defaults: { _controller: applicationequipmentBundle:form:addNewEquipmentSave }