applicationequipment_addEquip:
    path:     /add
    defaults: { _controller: applicationequipmentBundle:form:saveEquipment }
applicationequipment_addEquipForm:
    path:     /addEquip
    defaults: { _controller: applicationequipmentBundle:form:add }
applicationequipment_reportDamage:
    path:     /DamageDesc
    defaults: { _controller: applicationequipmentBundle:form:damageView }

applicationequipment_reportDamageView:
    path:     /saveDamage
    defaults: { _controller: applicationequipmentBundle:form:damageReport }
applicationequipment_addNewEquipView:
    path:     /addNewEquip
    defaults: { _controller: applicationequipmentBundle:form:addNewEquipment }
applicationequipment_addNewEquipsave:
    path:     /addNew

    defaults: { _controller: applicationequipmentBundle:form:addNewEquipmentSave }
applicationequipment_addNewSupplier:
    path:     /addSupplier

    defaults: { _controller: applicationequipmentBundle:form:addNewSupplier }
applicationequipment_saveNewSupplier:
    path:     /saveSupplier

    defaults: { _controller: applicationequipmentBundle:form:saveSupplier }
applicationequipment_requestProcess:
    path:     /requestProccess

    defaults: { _controller: applicationequipmentBundle:form:requestAcceptTable }
applicationequipment_requestResource:
    path:     /RequestResource

    defaults: { _controller: applicationequipmentBundle:form:requestResourceTable }
applicationequipment_approveRequest:
    path:     /approvals

    defaults: { _controller: applicationequipmentBundle:form:approval }
applicationequipment_viewAll:
    path:     /viewAllEquipments

    defaults: { _controller: applicationequipmentBundle:Default:viewAllEquipments }