sport_homepage:
    path:     /sport
    defaults: { _controller: SportBundle:Default:index }

sport-add:
    path: /sportadd
    defaults: {_controller: SportBundle:AddSportForm:addSport}

sport-add-database:
    path: /sport/save
    defaults: {_controller: SportBundle:AddSportForm:saveSport}
sport-view-schedule:
    path: /sport/view
    defaults: {_controller: SportBundle:ViewScheduleData:viewSchedule}
sport-view-gymschedule:
    path: /sport/Gym
    defaults: {_controller: SportBundle:GymSchedule:index}
sport-view-groundschedule:
    path: /sport/Ground
    defaults: {_controller: SportBundle:GroundSchedule:index}